model:
  name: "HousePricePredictor"
  target_variable: "price"
  best_model: "XGBoost"
  parameters:
    objective: "reg:squarederror"
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
